version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "8081:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: TesloDB
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
